version: '3'
services:
  api:
    build: docker/go-tools
    working_dir: /go/src/github.com/islavallee/librapi
    volumes:
      - ./:/go/src/github.com/islavallee/librapi
    ports:
      - "80:8080"
    command: reflex -r '\.go' -s go run main.go

